# Generated by Django 4.2.30 on 2026-04-20 22:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoVectorsNle',
            fields=[
                ('osm_key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name': 'GeoVectors NLE',
                'verbose_name_plural': 'GeoVectors NLE',
                'db_table': 'geovectors_nle',
            },
        ),
    ]
