# Generated by Django 4.2.30 on 2026-05-29 19:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpatialTripletScoreRejected',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('head_osm_type', models.CharField(db_index=True, max_length=10)),
                ('head_osm_id', models.BigIntegerField(db_index=True)),
                ('tail_osm_type', models.CharField(db_index=True, max_length=10)),
                ('tail_osm_id', models.BigIntegerField(db_index=True)),
                ('relation', models.CharField(db_index=True, help_text='Spatial relation (e.g., isInCounty, addrSuburb)', max_length=50)),
                ('geo_score', models.FloatField(help_text='Geohash distance score (precision by relation)')),
                ('name_score', models.FloatField(help_text='FastText cosine similarity (literal vs candidate name)')),
                ('topo_score', models.FloatField(help_text='TransE topological constraint score')),
                ('unnormalized_score', models.FloatField(db_index=True, default=0.0, help_text='Raw sum of geo + name + topo scores (range [0, 3.0])')),
                ('normalized_score', models.FloatField(db_index=True, default=0.0, help_text='Normalized score = unnormalized_score / 3.0 (range [0, 1.0])')),
                ('geohash_precision', models.IntegerField(help_text='Geohash precision used for geo_score')),
                ('snapshot_id', models.UUIDField(blank=True, db_index=True, help_text='TemporalSnapshot UUID that these links were generated from', null=True)),
                ('country_name', models.CharField(blank=True, db_index=True, help_text='Country name for this link (self-describing, independent of snapshot_id)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'igea_spatial_triplet_score_rejected',
                'ordering': ['-normalized_score'],
                'indexes': [models.Index(fields=['head_osm_type', 'head_osm_id'], name='igea_spatia_head_os_baf221_idx'), models.Index(fields=['tail_osm_type', 'tail_osm_id'], name='igea_spatia_tail_os_454558_idx'), models.Index(fields=['relation', 'unnormalized_score'], name='igea_spatia_relatio_ecbda9_idx'), models.Index(fields=['normalized_score'], name='igea_spatia_normali_8f5fdd_idx'), models.Index(fields=['snapshot_id'], name='igea_spatia_snapsho_c1fbd7_idx'), models.Index(fields=['country_name'], name='igea_spatia_country_5a4d0b_idx')],
                'unique_together': {('head_osm_type', 'head_osm_id', 'relation', 'tail_osm_type', 'tail_osm_id', 'snapshot_id', 'country_name')},
            },
        ),
        migrations.CreateModel(
            name='SpatialTripletScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('head_osm_type', models.CharField(db_index=True, max_length=10)),
                ('head_osm_id', models.BigIntegerField(db_index=True)),
                ('tail_osm_type', models.CharField(db_index=True, max_length=10)),
                ('tail_osm_id', models.BigIntegerField(db_index=True)),
                ('relation', models.CharField(db_index=True, help_text='Spatial relation (e.g., isInCounty, addrSuburb)', max_length=50)),
                ('geo_score', models.FloatField(help_text='Geohash distance score (precision by relation)')),
                ('name_score', models.FloatField(help_text='FastText cosine similarity (literal vs candidate name)')),
                ('topo_score', models.FloatField(help_text='TransE topological constraint score')),
                ('unnormalized_score', models.FloatField(db_index=True, default=0.0, help_text='Raw sum of geo + name + topo scores (range [0, 3.0])')),
                ('normalized_score', models.FloatField(db_index=True, default=0.0, help_text='Normalized score = unnormalized_score / 3.0 (range [0, 1.0])')),
                ('predicted', models.BooleanField(default=False, help_text='True if normalized_score >= ACCEPTANCE_THRESHOLD (0.7)')),
                ('geohash_precision', models.IntegerField(help_text='Geohash precision used for geo_score')),
                ('snapshot_id', models.UUIDField(blank=True, db_index=True, help_text='TemporalSnapshot UUID that these links were generated from', null=True)),
                ('country_name', models.CharField(blank=True, db_index=True, help_text='Country name for this link (self-describing, independent of snapshot_id)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'igea_spatial_triplet_score',
                'ordering': ['-normalized_score'],
                'indexes': [models.Index(fields=['head_osm_type', 'head_osm_id'], name='igea_spatia_head_os_9c738c_idx'), models.Index(fields=['tail_osm_type', 'tail_osm_id'], name='igea_spatia_tail_os_e88d67_idx'), models.Index(fields=['relation', 'unnormalized_score'], name='igea_spatia_relatio_c6b094_idx'), models.Index(fields=['normalized_score'], name='igea_spatia_normali_5918f8_idx'), models.Index(fields=['predicted'], name='igea_spatia_predict_65bcfe_idx'), models.Index(fields=['snapshot_id'], name='igea_spatia_snapsho_686241_idx'), models.Index(fields=['country_name'], name='igea_spatia_country_61c860_idx')],
                'unique_together': {('head_osm_type', 'head_osm_id', 'relation', 'tail_osm_type', 'tail_osm_id', 'snapshot_id', 'country_name')},
            },
        ),
        migrations.CreateModel(
            name='EntityAlignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('osm_type', models.CharField(db_index=True, max_length=10)),
                ('osm_id', models.BigIntegerField(db_index=True)),
                ('wikidata_uri', models.CharField(db_index=True, max_length=200)),
                ('wikidata_label', models.CharField(blank=True, max_length=500, null=True)),
                ('alignment_method', models.CharField(choices=[('SEED', 'Seed (wikidata= tag)'), ('COSINE', 'Cosine similarity baseline'), ('CROSS_ATTN', 'BiLSTM cross-attention')], help_text='Method used for alignment', max_length=20)),
                ('confidence', models.FloatField(help_text='Alignment confidence score (0.0-1.0)')),
                ('iteration', models.IntegerField(default=0, help_text='IGEA iteration when alignment was accepted')),
                ('distance_meters', models.FloatField(blank=True, help_text='Haversine distance between OSM and Wikidata coordinates', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'igea_entity_alignment',
                'ordering': ['-confidence', '-created_at'],
                'indexes': [models.Index(fields=['osm_type', 'osm_id'], name='igea_entity_osm_typ_c23274_idx'), models.Index(fields=['wikidata_uri'], name='igea_entity_wikidat_4bec54_idx'), models.Index(fields=['alignment_method', 'confidence'], name='igea_entity_alignme_7848e3_idx'), models.Index(fields=['created_at'], name='igea_entity_created_8e1eed_idx')],
                'unique_together': {('osm_type', 'osm_id', 'wikidata_uri')},
            },
        ),
    ]
