# Generated by Django 4.2.30 on 2026-08-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spatialtripletscore',
            name='snapshot_id',
            field=models.CharField(blank=True, db_index=True, help_text='Snapshot date (YYYY_MM_DD) these links were generated from. Matches OsmEntity.snapshot_id for partition-scoped queries.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='spatialtripletscorerejected',
            name='snapshot_id',
            field=models.CharField(blank=True, db_index=True, help_text='Snapshot date (YYYY_MM_DD) these links were generated from. Matches OsmEntity.snapshot_id for partition-scoped queries.', max_length=20, null=True),
        ),
    ]
