# Generated by Django 4.2.30 on 2026-08-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igea', '0002_alter_spatialtripletscore_snapshot_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='spatialtripletscore',
            index=models.Index(fields=['country_name', 'snapshot_id', 'predicted'], name='igea_triplet_csp_idx'),
        ),
    ]
