# Generated by Django 4.2.30 on 2026-07-01 22:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import pgvector.django
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CensusTract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geouid', models.CharField(db_index=True, help_text='Geographic UID following Geofabrik hierarchy: country-region-tract', max_length=100, unique=True)),
                ('name', models.CharField(help_text="Human-readable name (e.g., 'Toronto Downtown Core')", max_length=200)),
                ('country', models.CharField(db_index=True, help_text="Country name (e.g., 'canada', 'united-states')", max_length=100)),
                ('region', models.CharField(blank=True, db_index=True, help_text="Region/state name (e.g., 'ontario', 'california')", max_length=100, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(help_text='WGS84 Polygon representing tract boundaries', srid=4326)),
                ('semantic_embedding', pgvector.django.VectorField(dimensions=300, help_text='L2-Normalized Weighted Average of OSM GeoVectors')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('embedding_version', models.CharField(default='1.0', help_text='Version of embedding algorithm used', max_length=20)),
            ],
            options={
                'verbose_name': 'Census Tract',
                'verbose_name_plural': 'Census Tracts',
                'db_table': 'semantic_search_censustract',
                'ordering': ['country', 'region', 'geouid'],
            },
        ),
        migrations.CreateModel(
            name='DriftScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('drift_score', models.FloatField(help_text='Cosine distance from base amenity vector (0=identical, 1=opposite)')),
                ('is_alert', models.BooleanField(default=False, help_text='True if drift exceeded threshold (default: 0.10)')),
                ('amenity_profile', models.JSONField(default=dict, help_text='Current amenity tag counts at time of measurement')),
            ],
            options={
                'verbose_name': 'Drift Score',
                'verbose_name_plural': 'Drift Scores',
                'db_table': 'semantic_search_driftscore',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EmbeddingComparison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_name', models.CharField(help_text='Name of the test or benchmark', max_length=255)),
                ('method', models.CharField(choices=[('fasttext_baseline', 'FastText Weighted Average'), ('hidden_state_projection', 'DistilGPT2 Hidden State + Projection')], help_text='Embedding method used', max_length=50)),
                ('query_tags', models.JSONField(help_text='Tag counts used for the query')),
                ('query_text', models.TextField(blank=True, help_text='Natural language query (for GPT methods)', null=True)),
                ('inference_time_ms', models.FloatField(help_text='Inference time in milliseconds')),
                ('memory_mb', models.FloatField(blank=True, help_text='CPU memory usage in MB', null=True)),
                ('gpu_memory_mb', models.FloatField(blank=True, help_text='GPU memory usage in MB', null=True)),
                ('top_5_results', models.JSONField(help_text='Top 5 retrieved census tracts with scores')),
                ('top_1_similarity', models.FloatField(help_text='Similarity score of top-1 result')),
                ('recall_at_5', models.FloatField(blank=True, help_text='Recall@5 metric', null=True)),
                ('recall_at_10', models.FloatField(blank=True, help_text='Recall@10 metric', null=True)),
                ('mrr', models.FloatField(blank=True, help_text='Mean Reciprocal Rank', null=True)),
                ('ndcg_at_10', models.FloatField(blank=True, help_text='Normalized Discounted Cumulative Gain @10', null=True)),
                ('overlap_at_5', models.FloatField(blank=True, help_text='Jaccard overlap with FastText top-5 results', null=True)),
                ('overlap_at_10', models.FloatField(blank=True, help_text='Jaccard overlap with FastText top-10 results', null=True)),
                ('rank_correlation', models.FloatField(blank=True, help_text="Spearman's rank correlation with FastText", null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Embedding Comparison',
                'verbose_name_plural': 'Embedding Comparisons',
                'db_table': 'semantic_search_embeddingcomparison',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProjectionHeadCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(help_text="Model version identifier, e.g., 'v1.0'", max_length=50)),
                ('model_state', models.BinaryField(help_text='PyTorch state_dict serialized as bytes')),
                ('optimizer_state', models.BinaryField(blank=True, help_text='Optimizer state_dict for resuming training', null=True)),
                ('epoch', models.IntegerField(help_text='Training epoch when checkpoint was saved')),
                ('train_loss', models.FloatField(help_text='Training loss at checkpoint')),
                ('val_loss', models.FloatField(blank=True, help_text='Validation loss at checkpoint', null=True)),
                ('config', models.JSONField(help_text='Model configuration (architecture, hyperparameters)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Projection Head Checkpoint',
                'verbose_name_plural': 'Projection Head Checkpoints',
                'db_table': 'semantic_search_projectionheadcheckpoint',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('epoch', models.IntegerField(help_text='Training epoch')),
                ('batch_idx', models.IntegerField(help_text='Batch index within epoch')),
                ('loss_total', models.FloatField(help_text='Total combined loss')),
                ('loss_alignment', models.FloatField(help_text='Alignment loss component')),
                ('loss_contrastive', models.FloatField(help_text='Contrastive (InfoNCE) loss component')),
                ('loss_rank_distillation', models.FloatField(blank=True, help_text='Rank distillation loss component', null=True)),
                ('learning_rate', models.FloatField(help_text='Current learning rate')),
                ('gradient_norm', models.FloatField(blank=True, help_text='Gradient norm (for monitoring)', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('checkpoint', models.ForeignKey(help_text='Associated checkpoint', on_delete=django.db.models.deletion.CASCADE, related_name='training_metrics', to='semantic_search.projectionheadcheckpoint')),
            ],
            options={
                'verbose_name': 'Training Metric',
                'verbose_name_plural': 'Training Metrics',
                'db_table': 'semantic_search_trainingmetrics',
                'ordering': ['checkpoint', 'epoch', 'batch_idx'],
            },
        ),
        migrations.CreateModel(
            name='SpatialLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('head_osm_id', models.BigIntegerField(db_index=True, help_text='OSM ID of the head (subject) entity')),
                ('relation_name', models.CharField(db_index=True, help_text="Predicted relation (e.g. 'isInCountry', 'addrCity')", max_length=100)),
                ('tail_osm_id', models.BigIntegerField(db_index=True, help_text='OSM ID of the predicted tail (object) entity')),
                ('literal_value', models.CharField(blank=True, default='', help_text='Original literal string from which the tail was predicted', max_length=500)),
                ('confidence', models.FloatField(help_text='USLP total score (geo + name + class spaces, range ~0–3)')),
                ('method', models.CharField(choices=[('USLP', 'Unsupervised Spatial Link Prediction (USLP)'), ('SSLP', 'Supervised Spatial Link Prediction (SSLP)'), ('MANUAL', 'Manually verified')], default='USLP', max_length=20)),
                ('source_snapshot_id', models.UUIDField(blank=True, db_index=True, help_text='TemporalSnapshot that produced this prediction', null=True)),
                ('verified', models.BooleanField(default=False, help_text='True after manual or automated verification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Spatial Link',
                'verbose_name_plural': 'Spatial Links',
                'db_table': 'semantic_search_spatiallink',
                'ordering': ['-confidence'],
                'indexes': [models.Index(fields=['head_osm_id', 'relation_name'], name='semantic_se_head_os_a21fea_idx'), models.Index(fields=['tail_osm_id'], name='semantic_se_tail_os_da7c82_idx'), models.Index(fields=['confidence'], name='semantic_se_confide_fde453_idx'), models.Index(fields=['source_snapshot_id'], name='semantic_se_source__3af7b0_idx'), models.Index(fields=['verified'], name='semantic_se_verifie_e6b931_idx'), models.Index(fields=['-created_at'], name='semantic_se_created_d2da28_idx')],
                'unique_together': {('head_osm_id', 'relation_name', 'tail_osm_id')},
            },
        ),
        migrations.CreateModel(
            name='SnapshotDiff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_id', models.UUIDField(db_index=True, help_text='UUID of the TemporalSnapshot that produced this diff')),
                ('prev_snapshot_id', models.UUIDField(blank=True, help_text='UUID of the previous TemporalSnapshot (None = first run)', null=True)),
                ('country_code', models.CharField(blank=True, default='', max_length=10)),
                ('country_name', models.CharField(blank=True, default='', max_length=100)),
                ('entities_added', models.IntegerField(default=0, help_text='New OSM entity rows inserted')),
                ('entities_modified', models.IntegerField(default=0, help_text='Existing entities with changed tags')),
                ('entities_deleted', models.IntegerField(default=0, help_text='Entities present in prev_snapshot but absent in current')),
                ('entities_re_embedded', models.IntegerField(default=0, help_text='Entities whose GV-Tags embedding was refreshed')),
                ('gv_nle_inductive_count', models.IntegerField(default=0, help_text='Entities that received an inductive (provisional) GV-NLE embedding')),
                ('gv_nle_retrained', models.BooleanField(default=False, help_text='True if full DeepWalk retraining was run this cycle')),
                ('spatial_links_predicted', models.IntegerField(default=0, help_text='SpatialLink records created by USLP this cycle')),
                ('wikidata_links_added', models.IntegerField(default=0, help_text='OsmEntity.wikidata_uri fields updated by IGEA this cycle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Snapshot Diff',
                'verbose_name_plural': 'Snapshot Diffs',
                'db_table': 'semantic_search_snapshotdiff',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['snapshot_id'], name='semantic_se_snapsho_dadf4d_idx'), models.Index(fields=['-created_at'], name='semantic_se_created_1b4a7a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectionTrainingPair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag_counts', models.JSONField(help_text="OSM tag counts, e.g., {'cafe': 40, 'residential': 30}")),
                ('query_text', models.TextField(help_text='Natural language query generated from tags')),
                ('teacher_embedding', pgvector.django.VectorField(dimensions=300, help_text='FastText weighted average embedding (teacher)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ground_truth_tract', models.ForeignKey(blank=True, help_text='Known relevant census tract for this query', null=True, on_delete=django.db.models.deletion.SET_NULL, to='semantic_search.censustract')),
            ],
            options={
                'verbose_name': 'Projection Training Pair',
                'verbose_name_plural': 'Projection Training Pairs',
                'db_table': 'semantic_search_projectiontrainingpair',
            },
        ),
        migrations.AddIndex(
            model_name='projectionheadcheckpoint',
            index=models.Index(fields=['version', '-epoch'], name='semantic_se_version_c23c2a_idx'),
        ),
        migrations.AddIndex(
            model_name='projectionheadcheckpoint',
            index=models.Index(fields=['-created_at'], name='semantic_se_created_9e3c88_idx'),
        ),
        migrations.AddIndex(
            model_name='embeddingcomparison',
            index=models.Index(fields=['method', 'test_name'], name='semantic_se_method_92cc8b_idx'),
        ),
        migrations.AddIndex(
            model_name='embeddingcomparison',
            index=models.Index(fields=['-timestamp'], name='semantic_se_timesta_6306d6_idx'),
        ),
        migrations.AddField(
            model_name='driftscore',
            name='census_tract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drift_scores', to='semantic_search.censustract'),
        ),
        migrations.AddIndex(
            model_name='censustract',
            index=models.Index(fields=['country', 'region'], name='semantic_se_country_aa499a_idx'),
        ),
        migrations.AddIndex(
            model_name='censustract',
            index=models.Index(fields=['geouid'], name='semantic_se_geouid_76a9b0_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingmetrics',
            index=models.Index(fields=['checkpoint', 'epoch', 'batch_idx'], name='semantic_se_checkpo_1fe114_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingmetrics',
            index=models.Index(fields=['-timestamp'], name='semantic_se_timesta_f4d1fb_idx'),
        ),
        migrations.AddIndex(
            model_name='projectiontrainingpair',
            index=models.Index(fields=['created_at'], name='semantic_se_created_ee5ef0_idx'),
        ),
        migrations.AddIndex(
            model_name='driftscore',
            index=models.Index(fields=['census_tract', '-timestamp'], name='semantic_se_census__65071a_idx'),
        ),
        migrations.AddIndex(
            model_name='driftscore',
            index=models.Index(fields=['is_alert', '-timestamp'], name='semantic_se_is_aler_71f22d_idx'),
        ),
    ]
