# Generated by Django 4.2.30 on 2026-08-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semantic_search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshotdiff',
            name='prev_snapshot_id',
            field=models.UUIDField(blank=True, help_text='UUID of the previous Snapshot (None = first run)', null=True),
        ),
        migrations.AlterField(
            model_name='snapshotdiff',
            name='snapshot_id',
            field=models.UUIDField(db_index=True, help_text='UUID of the Snapshot that produced this diff'),
        ),
        migrations.AlterField(
            model_name='spatiallink',
            name='source_snapshot_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Snapshot that produced this prediction', null=True),
        ),
    ]
