# Generated by Django 4.2.30 on 2026-08-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semantic_search', '0003_graph_spectral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphspectraldrift',
            name='region',
            field=models.CharField(db_index=True, help_text='Country code or subgraph slug for subdivision-scoped analysis', max_length=255),
        ),
        migrations.AlterField(
            model_name='graphspectralfingerprint',
            name='region',
            field=models.CharField(db_index=True, help_text='Country code or subgraph slug for subdivision-scoped analysis', max_length=255),
        ),
    ]
