# Generated by Django 4.2.30 on 2026-09-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semantic_search', '0005_delete_projection_experiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphspectralfingerprint',
            name='community_count',
            field=models.IntegerField(blank=True, help_text='Louvain community count for this region and snapshot. Persisted by Step 5c (Part 2 prerequisite 0c, 2026-09-11).', null=True),
        ),
        migrations.AddField(
            model_name='graphspectralfingerprint',
            name='modularity',
            field=models.FloatField(blank=True, help_text='Louvain modularity Q for this region and snapshot. Persisted by Step 5c (Part 2 prerequisite 0c, 2026-09-11).', null=True),
        ),
    ]
