# Generated by Django 4.2.30 on 2026-09-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semantic_search', '0006_graphspectralfingerprint_community_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(db_index=True, max_length=8)),
                ('subdivision_qid', models.CharField(blank=True, db_index=True, default='', max_length=16)),
                ('subdivision_name', models.CharField(blank=True, default='', max_length=255)),
                ('question', models.TextField()),
                ('template', models.CharField(default='', max_length=64)),
                ('anchor', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(default='generated', max_length=16)),
                ('snapshot_date', models.CharField(blank=True, default='', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sample Question',
                'verbose_name_plural': 'Sample Questions',
                'db_table': 'semantic_search_samplequestion',
                'ordering': ['country_code', 'subdivision_qid', 'question'],
                'indexes': [models.Index(fields=['country_code', 'subdivision_qid'], name='semantic_se_country_b0e58e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='samplequestion',
            constraint=models.UniqueConstraint(fields=('country_code', 'subdivision_qid', 'question'), name='uniq_sample_question'),
        ),
    ]
