# Generated by Django 4.2.30 on 2026-08-03 20:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetBundle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('bundle_path', models.CharField(help_text='Directory path containing asset files', max_length=1024)),
                ('node_count', models.IntegerField(default=0)),
                ('way_count', models.IntegerField(default=0)),
                ('relation_count', models.IntegerField(default=0)),
                ('edge_count', models.IntegerField(default=0)),
                ('tag_count', models.IntegerField(default=0)),
                ('total_size_bytes', models.BigIntegerField(blank=True, help_text='Total size of all asset files in bytes', null=True)),
                ('generation_time_seconds', models.FloatField(blank=True, help_text='Time taken to generate this asset bundle', null=True)),
                ('tag_key', models.CharField(blank=True, db_index=True, help_text='OSM tag key (building, amenity, highway, etc.)', max_length=100, null=True)),
                ('name', models.CharField(blank=True, db_index=True, help_text='Optional descriptive name for this asset bundle', max_length=200, null=True)),
                ('data_quality_score', models.FloatField(blank=True, help_text='Quality score based on completeness, consistency', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'asset_bundles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PbfTagDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_key', models.CharField(db_index=True, max_length=255)),
                ('tag_value', models.CharField(db_index=True, max_length=255)),
                ('count', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pbf_tag_distributions',
                'ordering': ['-count'],
            },
        ),
        migrations.CreateModel(
            name='TemporalSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('region', models.CharField(db_index=True, max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('snapshot_interval', models.CharField(choices=[('WEEKLY', 'Weekly (every 7 days)'), ('BIWEEKLY', 'Biweekly (every 14 days)'), ('MONTHLY', 'Monthly (last day of month)'), ('CUSTOM', 'Custom date')], default='MONTHLY', help_text='Interval type for this snapshot', max_length=20)),
                ('file_path', models.CharField(blank=True, help_text='Optional: Path to snapshot PBF if generated', max_length=1024, null=True, unique=True)),
                ('filter_config', models.JSONField(blank=True, help_text='Filter configuration (target_tags, etc.) for filtered snapshots', null=True)),
                ('filter_hash', models.CharField(blank=True, db_index=True, help_text='MD5 hash of filter_config for uniqueness constraint', max_length=64, null=True)),
                ('node_count', models.BigIntegerField(default=0)),
                ('way_count', models.BigIntegerField(default=0)),
                ('relation_count', models.BigIntegerField(default=0)),
                ('fasttext_model_path', models.CharField(blank=True, max_length=512, null=True)),
                ('nle_model_path', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'temporal_snapshots',
                'ordering': ['region', 'timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WorldKGClassDrift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('region', models.CharField(db_index=True, max_length=255)),
                ('bbox', models.JSONField(help_text='Bounding box as [min_lon, min_lat, max_lon, max_lat]')),
                ('class_distribution_from', models.JSONField(help_text='WorldKG class distribution at t0: {class: count}')),
                ('class_distribution_to', models.JSONField(help_text='WorldKG class distribution at t1: {class: count}')),
                ('kl_divergence', models.FloatField(help_text='KL divergence between class distributions')),
                ('js_divergence', models.FloatField(help_text='Jensen-Shannon divergence (symmetric)')),
                ('depth_delta', models.FloatField(help_text='Change in mean ontology depth (negative = generalization)')),
                ('new_classes', models.JSONField(help_text='Classes appearing in t1 but not t0')),
                ('lost_classes', models.JSONField(help_text='Classes in t0 but not t1')),
                ('dominant_shift', models.JSONField(help_text='Largest class proportion changes: {class: delta}')),
                ('drift_magnitude', models.CharField(choices=[('low', 'Low (<0.1)'), ('medium', 'Medium (0.1-0.3)'), ('high', 'High (0.3-0.5)'), ('extreme', 'Extreme (>0.5)')], help_text='Categorical drift magnitude based on JS divergence', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'worldkg_class_drift',
                'ordering': ['region', 'snapshot_from__timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WorldKGClassFingerprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('region', models.CharField(db_index=True, max_length=255)),
                ('class_distribution', models.JSONField(help_text='Normalized class distribution: {class: percentage}')),
                ('mean_depth', models.FloatField(help_text='Mean ontology depth across all entities')),
                ('depth_std', models.FloatField(help_text='Standard deviation of ontology depth')),
                ('unique_classes', models.IntegerField(help_text='Number of unique WorldKG classes present')),
                ('shannon_entropy', models.FloatField(help_text='Shannon entropy of class distribution (semantic diversity)')),
                ('simpson_index', models.FloatField(help_text="Simpson's diversity index")),
                ('top_5_classes', models.JSONField(help_text='Top 5 most common classes with percentages')),
                ('total_entities', models.BigIntegerField(help_text='Total entities with WorldKG classification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'worldkg_class_fingerprint',
                'ordering': ['region', 'snapshot__timestamp'],
            },
        ),
    ]
