# Generated by Django 4.2.30 on 2026-08-03 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        ('orchestration', '0001_initial'),
        ('extraction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldkgclassfingerprint',
            name='processing_session',
            field=models.ForeignKey(blank=True, help_text='Pipeline session that generated this fingerprint', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wkg_fingerprints', to='orchestration.processingsession'),
        ),
        migrations.AddField(
            model_name='worldkgclassfingerprint',
            name='snapshot',
            field=models.ForeignKey(help_text='Temporal snapshot this fingerprint represents', on_delete=django.db.models.deletion.CASCADE, related_name='wkg_fingerprints', to='analysis.temporalsnapshot'),
        ),
        migrations.AddField(
            model_name='worldkgclassdrift',
            name='processing_session',
            field=models.ForeignKey(blank=True, help_text='Pipeline session that computed this drift', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wkg_class_drifts', to='orchestration.processingsession'),
        ),
        migrations.AddField(
            model_name='worldkgclassdrift',
            name='snapshot_from',
            field=models.ForeignKey(help_text='Earlier temporal snapshot', on_delete=django.db.models.deletion.CASCADE, related_name='wkg_drift_from', to='analysis.temporalsnapshot'),
        ),
        migrations.AddField(
            model_name='worldkgclassdrift',
            name='snapshot_to',
            field=models.ForeignKey(help_text='Later temporal snapshot', on_delete=django.db.models.deletion.CASCADE, related_name='wkg_drift_to', to='analysis.temporalsnapshot'),
        ),
        migrations.AddField(
            model_name='temporalsnapshot',
            name='pbf_file',
            field=models.ForeignKey(help_text='Source temporal extract (monthly or yearly)', on_delete=django.db.models.deletion.CASCADE, related_name='temporal_snapshots', to='extraction.pbffile'),
        ),
        migrations.AddField(
            model_name='temporalsnapshot',
            name='processing_session',
            field=models.ForeignKey(blank=True, help_text='Pipeline session that created this snapshot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temporal_snapshots', to='orchestration.processingsession'),
        ),
        migrations.AddField(
            model_name='pbftagdistribution',
            name='pbf_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_distributions', to='extraction.pbffile'),
        ),
        migrations.AddField(
            model_name='pbftagdistribution',
            name='processing_session',
            field=models.ForeignKey(blank=True, help_text='Pipeline session that produced this tag distribution', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_distributions', to='orchestration.processingsession'),
        ),
        migrations.AddField(
            model_name='assetbundle',
            name='processing_session',
            field=models.ForeignKey(blank=True, help_text='Pipeline session that generated this asset bundle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_bundles', to='orchestration.processingsession'),
        ),
        migrations.AddField(
            model_name='assetbundle',
            name='source_monthly_extract',
            field=models.ForeignKey(blank=True, help_text='Original monthly extract this was derived from', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_asset_bundles', to='extraction.pbffile'),
        ),
        migrations.AddField(
            model_name='assetbundle',
            name='temporal_snapshot',
            field=models.ForeignKey(help_text='Associated temporal snapshot', on_delete=django.db.models.deletion.CASCADE, related_name='asset_bundles', to='analysis.temporalsnapshot'),
        ),
        migrations.AddIndex(
            model_name='worldkgclassfingerprint',
            index=models.Index(fields=['region', 'snapshot'], name='worldkg_cla_region_6bf778_idx'),
        ),
        migrations.AddIndex(
            model_name='worldkgclassfingerprint',
            index=models.Index(fields=['shannon_entropy'], name='worldkg_cla_shannon_61dd5a_idx'),
        ),
        migrations.AddIndex(
            model_name='worldkgclassfingerprint',
            index=models.Index(fields=['mean_depth'], name='worldkg_cla_mean_de_8d5a44_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='worldkgclassfingerprint',
            unique_together={('region', 'snapshot')},
        ),
        migrations.AddIndex(
            model_name='worldkgclassdrift',
            index=models.Index(fields=['region', 'drift_magnitude'], name='worldkg_cla_region_68effb_idx'),
        ),
        migrations.AddIndex(
            model_name='worldkgclassdrift',
            index=models.Index(fields=['snapshot_from', 'snapshot_to'], name='worldkg_cla_snapsho_2abece_idx'),
        ),
        migrations.AddIndex(
            model_name='worldkgclassdrift',
            index=models.Index(fields=['-js_divergence'], name='worldkg_cla_js_dive_0f381f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='worldkgclassdrift',
            unique_together={('region', 'snapshot_from', 'snapshot_to')},
        ),
        migrations.AddIndex(
            model_name='temporalsnapshot',
            index=models.Index(fields=['region', 'timestamp'], name='temporal_sn_region_dbe5ae_idx'),
        ),
        migrations.AddIndex(
            model_name='temporalsnapshot',
            index=models.Index(fields=['pbf_file', 'snapshot_interval'], name='temporal_sn_pbf_fil_566419_idx'),
        ),
        migrations.AddIndex(
            model_name='temporalsnapshot',
            index=models.Index(fields=['snapshot_interval', 'created_at'], name='temporal_sn_snapsho_12fa31_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='temporalsnapshot',
            unique_together={('region', 'timestamp', 'snapshot_interval', 'filter_hash')},
        ),
        migrations.AddIndex(
            model_name='pbftagdistribution',
            index=models.Index(fields=['tag_key', 'tag_value'], name='pbf_tag_dis_tag_key_02c833_idx'),
        ),
        migrations.AddIndex(
            model_name='pbftagdistribution',
            index=models.Index(fields=['pbf_file', 'count'], name='pbf_tag_dis_pbf_fil_b89388_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pbftagdistribution',
            unique_together={('pbf_file', 'tag_key', 'tag_value')},
        ),
        migrations.AddIndex(
            model_name='assetbundle',
            index=models.Index(fields=['temporal_snapshot', 'created_at'], name='asset_bundl_tempora_7176e9_idx'),
        ),
        migrations.AddIndex(
            model_name='assetbundle',
            index=models.Index(fields=['created_at'], name='asset_bundl_created_0084d7_idx'),
        ),
        migrations.AddIndex(
            model_name='assetbundle',
            index=models.Index(fields=['tag_key', 'created_at'], name='asset_bundl_tag_key_98159c_idx'),
        ),
        migrations.AddIndex(
            model_name='assetbundle',
            index=models.Index(fields=['source_monthly_extract', 'tag_key'], name='asset_bundl_source__750386_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assetbundle',
            unique_together={('temporal_snapshot', 'tag_key')},
        ),
    ]
