# Generated by Django 4.2.30 on 2026-04-25 18:10

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import pgvector.django


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OsmEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_type', models.CharField(choices=[('node', 'Node'), ('way', 'Way'), ('relation', 'Relation')], help_text='OSM element type (node, way, relation)', max_length=10)),
                ('osm_id', models.BigIntegerField(help_text='OSM element ID')),
                ('tags', models.JSONField(help_text="OSM tags as key-value pairs, e.g., {'amenity': 'cafe', 'name': 'Starbucks'}")),
                ('gv_tags_embedding', pgvector.django.VectorField(blank=True, dimensions=300, help_text='GV-Tags: Semantic embedding from FastText (What you are)', null=True)),
                ('gv_nle_embedding', pgvector.django.VectorField(blank=True, dimensions=100, help_text='GV-NLE: Spatial embedding from k-NN graph (Where you are)', null=True)),
                ('wkg_class', models.CharField(blank=True, db_index=True, help_text="WorldKG ontological class using wkgs: namespace (e.g., 'wkgs:Cafe', 'wkgs:Hospital'). Corresponds to rdf:type assertion in WorldKG RDF triples.", max_length=200, null=True)),
                ('wkg_superclasses', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, help_text="WorldKG class hierarchy path using wkgs: namespace (e.g., ['wkgs:Cafe', 'wkgs:Amenity', 'wkgs:WKGObject']). Derived from rdfs:subClassOf chain in the WorldKG ontology.", null=True, size=None)),
                ('wikidata_uri', models.CharField(blank=True, db_index=True, help_text="Wikidata equivalent class URI via NCA alignment (owl:equivalentClass on the class, not owl:sameAs on the instance). E.g., 'http://www.wikidata.org/entity/Q11707'.", max_length=200, null=True)),
                ('wkg_depth', models.IntegerField(blank=True, help_text='Depth in WorldKG ontology tree: 0=wkgs:WKGObject, 1=key class, 2=value subclass', null=True)),
                ('wkg_type_key', models.CharField(blank=True, help_text="OSM key that determined the WorldKG class assignment (e.g., 'amenity'). Distinguishes type-asserting tags from property tags per WorldKG Section 4.2.", max_length=100, null=True)),
                ('wkg_type_value', models.CharField(blank=True, help_text="OSM value that determined the WorldKG class assignment (e.g., 'restaurant'). Null for top-level key classes (e.g., building=yes → wkgs:Building).", max_length=100, null=True)),
                ('wkg_enriched_at', models.DateTimeField(blank=True, help_text='Timestamp when WorldKG enrichment was performed', null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='WGS84 Point geometry (for nodes)', null=True, srid=4326)),
                ('version', models.IntegerField(blank=True, help_text='OSM element version', null=True)),
                ('timestamp', models.DateTimeField(blank=True, help_text='OSM element timestamp', null=True)),
                ('gv_tags_version', models.CharField(default='1.0', help_text='GV-Tags FastText model version', max_length=20)),
                ('gv_nle_version', models.CharField(blank=True, help_text='GV-NLE trained model version', max_length=20, null=True)),
                ('gv_nle_trained', models.BooleanField(default=False, help_text='Has GV-NLE embedding been computed?')),
                ('source_snapshot_id', models.UUIDField(blank=True, db_index=True, help_text='UUID of source TemporalSnapshot (cross-database reference)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OSM Entity',
                'verbose_name_plural': 'OSM Entities',
                'db_table': 'semantic_search_osmentity',
                'ordering': ['osm_type', 'osm_id'],
                'indexes': [models.Index(fields=['osm_type', 'osm_id'], name='semantic_se_osm_typ_6d0830_idx'), models.Index(fields=['created_at'], name='semantic_se_created_af9489_idx'), models.Index(fields=['source_snapshot_id', 'gv_nle_trained'], name='semantic_se_source__103806_idx'), models.Index(fields=['wkg_class'], name='semantic_se_wkg_cla_4ccc79_idx'), models.Index(fields=['wikidata_uri'], name='semantic_se_wikidat_18aa57_idx'), models.Index(fields=['wkg_depth'], name='semantic_se_wkg_dep_f95c43_idx'), models.Index(fields=['wkg_type_key', 'wkg_type_value'], name='semantic_se_wkg_typ_17db0e_idx')],
                'unique_together': {('osm_type', 'osm_id', 'gv_tags_version')},
            },
        ),
    ]
