# Generated by Django 4.2.30 on 2026-04-30 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldkg_nca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osmentity',
            name='gv_nle_version',
            field=models.CharField(blank=True, help_text='GV-NLE trained model version', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='osmentity',
            name='gv_tags_version',
            field=models.CharField(default='1.0', help_text='GV-Tags FastText model version', max_length=50),
        ),
    ]
