# Generated by Django 4.2.25 on 2026-05-01 15:23

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('worldkg_nca', '0002_alter_osmentity_gv_nle_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osmentity',
            name='gv_nle_embedding',
            field=pgvector.django.VectorField(blank=True, dimensions=128, help_text='GV-NLE: Spatial embedding from k-NN graph (Where you are)', null=True),
        ),
    ]
