# Generated by Django 4.2.30 on 2026-05-02 01:15

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('worldkg_nca', '0003_alter_osmentity_gv_nle_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osmentity',
            name='gv_nle_embedding',
            field=pgvector.django.VectorField(blank=True, dimensions=100, help_text='GV-NLE: Spatial embedding from k-NN graph (Where you are)', null=True),
        ),
    ]
