# Generated by Django 4.2.30 on 2026-06-01 01:37

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('worldkg_nca', '0004_alter_osmentity_gv_nle_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='osmentity',
            name='static_embedding',
            field=pgvector.django.VectorField(blank=True, dimensions=400, help_text='Static embedding approximating fused geo+name+class score for ANN search (GV-Tags+GV-NLE)', null=True),
        ),
    ]
