# Generated by Django 4.2.25 on 2026-06-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldkg_nca', '0005_osmentity_static_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecomputedLinkCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(blank=True, db_index=True, default='', max_length=10)),
                ('osm_type', models.CharField(choices=[('node', 'Node'), ('way', 'Way'), ('relation', 'Relation')], max_length=10)),
                ('osm_id', models.BigIntegerField()),
                ('projection_asset_id', models.UUIDField(blank=True, null=True)),
                ('candidates', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'worldkg_precomputed_link_candidate',
                'indexes': [models.Index(fields=['country_code'], name='worldkg_pre_country_d103ac_idx'), models.Index(fields=['osm_type', 'osm_id'], name='worldkg_pre_osm_typ_5fcf77_idx')],
                'unique_together': {('osm_type', 'osm_id', 'projection_asset_id')},
            },
        ),
    ]
