# Generated by Django 4.2.30 on 2026-08-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldkg_nca', '0009_osmentity_cutover_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osmentity',
            name='snapshot_id',
            field=models.CharField(blank=True, help_text="Temporal partition key (YYYY_MM_DD, e.g. '2025_12_31'). Derived from source_snapshot_id → Snapshot.snapshot_date.", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='osmentity',
            name='source_snapshot_id',
            field=models.UUIDField(blank=True, help_text='UUID of source Snapshot (cross-database reference)', null=True),
        ),
    ]
