# Generated by Django 4.2.30 on 2026-08-19 01:45

import django.contrib.postgres.indexes
from django.db import migrations, models
import pgvector.django


# Migration 0011 created osmentity_tags_gin_idx via raw SQL
# (CREATE INDEX IF NOT EXISTS).  The model also declares the index in
# Meta.indexes, so makemigrations emitted a duplicate AddIndex here.
# We wrap it in SeparateDatabaseAndState so Django's migration state
# records the index (keeping makemigrations --check clean) without
# re-running the SQL, which would fail with DuplicateTable.


class Migration(migrations.Migration):

    dependencies = [
        ('worldkg_nca', '0011_osmentity_parent_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmenityEmbedding',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amenity_text', models.CharField(help_text='Amenity value from the MapQA vocabulary (lowercased)', max_length=100, unique=True)),
                ('embedding', pgvector.django.VectorField(dimensions=300, help_text='FastText 300D embedding (L2-normalized, GeoVectors space)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'factor_amenity_embedding',
                'ordering': ['amenity_text'],
            },
        ),
        migrations.CreateModel(
            name='DriftNodeMetric',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('country_code', models.CharField(help_text='ISO 3166-1 alpha-2 country code', max_length=3)),
                ('snapshot_from_id', models.CharField(help_text='Earlier snapshot date (YYYY_MM_DD)', max_length=20)),
                ('snapshot_to_id', models.CharField(help_text='Later snapshot date (YYYY_MM_DD)', max_length=20)),
                ('osm_id', models.BigIntegerField(help_text='OSM element ID (present in both snapshots)')),
                ('fiedler_delta', models.FloatField(blank=True, help_text='phi2(t) - phi2(t-1) after eigenvector sign alignment', null=True)),
                ('loading_drift', models.FloatField(blank=True, help_text='Cosine distance between sign-aligned eigen-loading vectors across the pair in [0, 2]', null=True)),
                ('community_changed', models.BooleanField(blank=True, help_text='Louvain community membership changed across the pair', null=True)),
                ('degree_delta', models.IntegerField(blank=True, help_text='degree(t) - degree(t-1) in the k-NN graph', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'factor_drift_node_metric',
                'ordering': ['country_code', 'snapshot_from_id', 'snapshot_to_id', 'osm_id'],
            },
        ),
        migrations.CreateModel(
            name='SpectralNodeMetric',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('snapshot_id', models.CharField(help_text='Snapshot date (YYYY_MM_DD) - matches OsmEntity.snapshot_id', max_length=20)),
                ('country_code', models.CharField(help_text='ISO 3166-1 alpha-2 country code', max_length=3)),
                ('osm_id', models.BigIntegerField(help_text='OSM element ID (k-NN graph node key)')),
                ('eigen_loadings', pgvector.django.VectorField(blank=True, dimensions=128, help_text='Node row of Phi (phi1..phiK, zero-padded to 128)', null=True)),
                ('fiedler_component', models.FloatField(blank=True, help_text='phi2(node) - duplicated from eigen_loadings[0] for cheap scalar filtering/sorting without vector ops', null=True)),
                ('louvain_community', models.IntegerField(blank=True, help_text='Louvain community ID (CommunityDetectionService, Step 5c)', null=True)),
                ('dirichlet_contrib', models.FloatField(blank=True, help_text='Per-node local Dirichlet term s_i*(Ls)_i for the wkg_class graph signal', null=True)),
                ('degree', models.IntegerField(blank=True, help_text='Node degree in the k-NN graph', null=True)),
                ('clustering_coeff', models.FloatField(blank=True, help_text='Local clustering coefficient', null=True)),
                ('component_id', models.IntegerField(blank=True, help_text='Connected-component membership (0-indexed, arbitrary)', null=True)),
                ('component_size', models.IntegerField(blank=True, help_text='Size of the node connected component', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'factor_spectral_node_metric',
                'ordering': ['snapshot_id', 'country_code', 'osm_id'],
            },
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name='osmentity',
                    index=django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='osmentity_tags_gin_idx', opclasses=['jsonb_path_ops']),
                ),
            ],
            database_operations=[],
        ),
        migrations.AddIndex(
            model_name='spectralnodemetric',
            index=models.Index(fields=['snapshot_id', 'country_code', 'louvain_community'], name='factor_spec_community_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='spectralnodemetric',
            unique_together={('snapshot_id', 'country_code', 'osm_id')},
        ),
        migrations.AddIndex(
            model_name='driftnodemetric',
            index=models.Index(fields=['country_code', 'snapshot_from_id', 'snapshot_to_id'], name='factor_drift_pair_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='driftnodemetric',
            unique_together={('country_code', 'snapshot_from_id', 'snapshot_to_id', 'osm_id')},
        ),
    ]
