# Generated by Django 4.2.30 on 2026-08-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldkg_nca', '0012_amenityembedding_driftnodemetric_spectralnodemetric_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenityembedding',
            name='amenity_text',
            field=models.CharField(help_text='Amenity value from the MapQA vocabulary (lowercased)', max_length=200, unique=True),
        ),
    ]
