# Generated by Django 4.2.30 on 2026-08-19 02:05

from django.db import migrations, models
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('worldkg_nca', '0013_alter_amenityembedding_amenity_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driftnodemetric',
            name='degree_delta',
            field=models.IntegerField(blank=True, help_text='degree(t) − degree(t−1) in the k-NN graph', null=True),
        ),
        migrations.AlterField(
            model_name='driftnodemetric',
            name='fiedler_delta',
            field=models.FloatField(blank=True, help_text='φ₂(t) − φ₂(t−1) after eigenvector sign alignment', null=True),
        ),
        migrations.AlterField(
            model_name='driftnodemetric',
            name='loading_drift',
            field=models.FloatField(blank=True, help_text='Cosine distance between sign-aligned eigen-loading vectors across the pair ∈ [0, 2]', null=True),
        ),
        migrations.AlterField(
            model_name='spectralnodemetric',
            name='component_size',
            field=models.IntegerField(blank=True, help_text="Size of the node's connected component", null=True),
        ),
        migrations.AlterField(
            model_name='spectralnodemetric',
            name='dirichlet_contrib',
            field=models.FloatField(blank=True, help_text='Per-node local Dirichlet term s_i·(Ls)_i for the wkg_class graph signal', null=True),
        ),
        migrations.AlterField(
            model_name='spectralnodemetric',
            name='eigen_loadings',
            field=pgvector.django.VectorField(blank=True, dimensions=128, help_text="Node's row of Φ (φ₁..φ_K, zero-padded to 128)", null=True),
        ),
        migrations.AlterField(
            model_name='spectralnodemetric',
            name='fiedler_component',
            field=models.FloatField(blank=True, help_text='φ₂(node) — duplicated from eigen_loadings[0] for cheap scalar filtering/sorting without vector ops', null=True),
        ),
        migrations.AlterField(
            model_name='spectralnodemetric',
            name='snapshot_id',
            field=models.CharField(help_text='Snapshot date (YYYY_MM_DD) — matches OsmEntity.snapshot_id', max_length=20),
        ),
    ]
