# Generated by Django 4.2.30 on 2026-08-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldkg_nca', '0014_alter_driftnodemetric_degree_delta_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='spectralnodemetric',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='spectralnodemetric',
            name='subgraph_slug',
            field=models.CharField(blank=True, db_index=True, help_text='Subgraph slug for subdivision-scoped spectral analysis. Null for country-level (small territories).', max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='spectralnodemetric',
            unique_together={('snapshot_id', 'country_code', 'subgraph_slug', 'osm_id')},
        ),
        migrations.AddIndex(
            model_name='spectralnodemetric',
            index=models.Index(fields=['snapshot_id', 'country_code', 'subgraph_slug'], name='factor_spec_subgraph_idx'),
        ),
    ]
