# Generated by Django 4.2.30 on 2026-09-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldkg_nca', '0017_osmentity_name_romanized'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmenityClassMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amenity_text', models.CharField(help_text='OSM amenity value (lowercased, spaces → underscores)', max_length=200, unique=True)),
                ('wkg_class', models.CharField(help_text='WorldKG class (wkgs: namespace) the amenity resolves to', max_length=255)),
                ('support_count', models.IntegerField(blank=True, help_text="OsmEntity row count backing a 'data' mapping (None for 'ontology' mappings)", null=True)),
                ('source', models.CharField(help_text="'data' (aggregated from OsmEntity) | 'ontology' (TTL-derived)", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'factor_amenity_class_mapping',
                'ordering': ['amenity_text'],
            },
        ),
        migrations.AddField(
            model_name='spectralnodemetric',
            name='fingerprint_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='GraphSpectralFingerprint.id whose eigenbasis produced these loadings (UUID, not FK — the fingerprint lives on the default DB). Runtime coherence check: NULL = unverified (pre-migration row, lenient mode).', null=True),
        ),
    ]
