# Generated by Django 4.2.30 on 2026-08-17 17:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country_code', models.CharField(db_index=True, help_text="ISO 3166-1 alpha-2 country code (e.g., 'CA', 'JM').", max_length=3)),
                ('snapshot_date', models.CharField(db_index=True, help_text="Snapshot date in YYYY_MM_DD format (e.g., '2025_12_31').", max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pbf_file', models.ForeignKey(help_text='The flattened (no-history) PBF file for this snapshot.', on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.pbffile')),
            ],
            options={
                'db_table': 'osm_snapshots',
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='PbfTagDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_key', models.CharField(db_index=True, max_length=255)),
                ('tag_value', models.CharField(db_index=True, max_length=255)),
                ('count', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pbf_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_distributions', to='core.pbffile')),
                ('processing_session', models.ForeignKey(blank=True, help_text='Pipeline session that produced this tag distribution', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_distributions', to='core.processingsession')),
            ],
            options={
                'db_table': 'pbf_tag_distributions',
                'ordering': ['-count'],
            },
        ),
        migrations.CreateModel(
            name='GraphExtract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extract_path', models.CharField(help_text='Directory path containing nodes.parquet, edges.parquet, tags.parquet.', max_length=1024)),
                ('node_count', models.IntegerField(default=0)),
                ('way_count', models.IntegerField(default=0)),
                ('relation_count', models.IntegerField(default=0)),
                ('edge_count', models.IntegerField(default=0)),
                ('tag_count', models.IntegerField(default=0)),
                ('total_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ForeignKey(help_text='The snapshot this graph data was extracted from.', on_delete=django.db.models.deletion.CASCADE, related_name='graph_extracts', to='osmsnapshot.snapshot')),
            ],
            options={
                'db_table': 'graph_extracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorldKGClassFingerprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('region', models.CharField(db_index=True, max_length=255)),
                ('class_distribution', models.JSONField(help_text='Normalized class distribution: {class: percentage}')),
                ('mean_depth', models.FloatField(help_text='Mean ontology depth across all entities')),
                ('depth_std', models.FloatField(help_text='Standard deviation of ontology depth')),
                ('unique_classes', models.IntegerField(help_text='Number of unique WorldKG classes present')),
                ('shannon_entropy', models.FloatField(help_text='Shannon entropy of class distribution (semantic diversity)')),
                ('simpson_index', models.FloatField(help_text="Simpson's diversity index")),
                ('top_5_classes', models.JSONField(help_text='Top 5 most common classes with percentages')),
                ('total_entities', models.BigIntegerField(help_text='Total entities with WorldKG classification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processing_session', models.ForeignKey(blank=True, help_text='Pipeline session that generated this fingerprint', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wkg_fingerprints', to='core.processingsession')),
                ('snapshot', models.ForeignKey(help_text='Snapshot this fingerprint represents', on_delete=django.db.models.deletion.CASCADE, related_name='wkg_fingerprints', to='osmsnapshot.snapshot')),
            ],
            options={
                'db_table': 'worldkg_class_fingerprint',
                'ordering': ['region', 'snapshot__snapshot_date'],
                'indexes': [models.Index(fields=['region', 'snapshot'], name='worldkg_cla_region_6bf778_idx'), models.Index(fields=['shannon_entropy'], name='worldkg_cla_shannon_61dd5a_idx'), models.Index(fields=['mean_depth'], name='worldkg_cla_mean_de_8d5a44_idx')],
                'unique_together': {('region', 'snapshot')},
            },
        ),
        migrations.CreateModel(
            name='WorldKGClassDrift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('region', models.CharField(db_index=True, max_length=255)),
                ('bbox', models.JSONField(help_text='Bounding box as [min_lon, min_lat, max_lon, max_lat]')),
                ('class_distribution_from', models.JSONField(help_text='WorldKG class distribution at t0: {class: count}')),
                ('class_distribution_to', models.JSONField(help_text='WorldKG class distribution at t1: {class: count}')),
                ('kl_divergence', models.FloatField(help_text='KL divergence between class distributions')),
                ('js_divergence', models.FloatField(help_text='Jensen-Shannon divergence (symmetric)')),
                ('depth_delta', models.FloatField(help_text='Change in mean ontology depth (negative = generalization)')),
                ('new_classes', models.JSONField(help_text='Classes appearing in t1 but not t0')),
                ('lost_classes', models.JSONField(help_text='Classes in t0 but not t1')),
                ('dominant_shift', models.JSONField(help_text='Largest class proportion changes: {class: delta}')),
                ('drift_magnitude', models.CharField(choices=[('low', 'Low (<0.1)'), ('medium', 'Medium (0.1-0.3)'), ('high', 'High (0.3-0.5)'), ('extreme', 'Extreme (>0.5)')], help_text='Categorical drift magnitude based on JS divergence', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processing_session', models.ForeignKey(blank=True, help_text='Pipeline session that computed this drift', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wkg_class_drifts', to='core.processingsession')),
                ('snapshot_from', models.ForeignKey(help_text='Earlier snapshot', on_delete=django.db.models.deletion.CASCADE, related_name='wkg_drift_from', to='osmsnapshot.snapshot')),
                ('snapshot_to', models.ForeignKey(help_text='Later snapshot', on_delete=django.db.models.deletion.CASCADE, related_name='wkg_drift_to', to='osmsnapshot.snapshot')),
            ],
            options={
                'db_table': 'worldkg_class_drift',
                'ordering': ['region', 'snapshot_from__snapshot_date'],
                'indexes': [models.Index(fields=['region', 'drift_magnitude'], name='worldkg_cla_region_68effb_idx'), models.Index(fields=['snapshot_from', 'snapshot_to'], name='worldkg_cla_snapsho_2abece_idx'), models.Index(fields=['-js_divergence'], name='worldkg_cla_js_dive_0f381f_idx')],
                'unique_together': {('region', 'snapshot_from', 'snapshot_to')},
            },
        ),
        migrations.CreateModel(
            name='SnapshotJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_date', models.CharField(db_index=True, help_text="Snapshot date in YYYY_MM_DD format (e.g., '2025_12_31').", max_length=10)),
                ('country_code', models.CharField(db_index=True, help_text="ISO 3166-1 alpha-2 country code (e.g., 'JM').", max_length=3)),
                ('country_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('total_entities', models.BigIntegerField(default=0)),
                ('total_aligned', models.BigIntegerField(default=0)),
                ('total_spatial_links', models.BigIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pipeline_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshot_jobs', to='core.pipelinerun')),
            ],
            options={
                'db_table': 'snapshot_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['snapshot_date', 'status'], name='snapshot_jo_snapsho_3c8881_idx'), models.Index(fields=['country_code', 'status'], name='snapshot_jo_country_4bf272_idx')],
                'unique_together': {('snapshot_date', 'country_code')},
            },
        ),
        migrations.AddIndex(
            model_name='snapshot',
            index=models.Index(fields=['country_code', 'snapshot_date'], name='osm_snapsho_country_071440_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='snapshot',
            unique_together={('country_code', 'snapshot_date')},
        ),
        migrations.AddIndex(
            model_name='pbftagdistribution',
            index=models.Index(fields=['tag_key', 'tag_value'], name='pbf_tag_dis_tag_key_02c833_idx'),
        ),
        migrations.AddIndex(
            model_name='pbftagdistribution',
            index=models.Index(fields=['pbf_file', 'count'], name='pbf_tag_dis_pbf_fil_b89388_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pbftagdistribution',
            unique_together={('pbf_file', 'tag_key', 'tag_value')},
        ),
        migrations.AlterUniqueTogether(
            name='graphextract',
            unique_together={('snapshot',)},
        ),
    ]
