# Generated by Django 4.2.30 on 2026-08-15 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extraction', '0001_initial'),
        ('orchestration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pbfextract',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pbf_extracts', to='orchestration.task'),
        ),
        migrations.AddField(
            model_name='pbfcollection',
            name='pbf_files',
            field=models.ManyToManyField(blank=True, to='extraction.pbffile'),
        ),
        migrations.AddField(
            model_name='osmwikidatahierarchy',
            name='region_hierarchy',
            field=models.OneToOneField(blank=True, help_text='Link to RegionHierarchy for continent recipe integration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='osm_wikidata_hierarchy', to='extraction.regionhierarchy'),
        ),
        migrations.AddField(
            model_name='osmboundary',
            name='polygon_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='osm_boundary', to='extraction.polygonfile'),
        ),
        migrations.AlterUniqueTogether(
            name='regionhierarchy',
            unique_together={('parent', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='regionalextractionstate',
            unique_together={('source_planet_path', 'poly_file')},
        ),
        migrations.AddIndex(
            model_name='projectionweightasset',
            index=models.Index(fields=['country_code'], name='projection__country_b350cb_idx'),
        ),
        migrations.AddIndex(
            model_name='projectionweightasset',
            index=models.Index(fields=['region_name'], name='projection__region__a75c61_idx'),
        ),
        migrations.AddIndex(
            model_name='projectionweightasset',
            index=models.Index(fields=['status'], name='projection__status_bc78d0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectionweightasset',
            unique_together={('country_code', 'region_name')},
        ),
        migrations.AddIndex(
            model_name='planetarymetrics',
            index=models.Index(fields=['pbf_file'], name='planetary_m_pbf_fil_8eabf3_idx'),
        ),
        migrations.AddIndex(
            model_name='planetarymetrics',
            index=models.Index(fields=['osm_wikidata_hierarchy'], name='planetary_m_osm_wik_2957a7_idx'),
        ),
        migrations.AddIndex(
            model_name='pbffile',
            index=models.Index(fields=['status'], name='pbf_files_status_81f0ac_idx'),
        ),
        migrations.AddIndex(
            model_name='pbffile',
            index=models.Index(fields=['pbf_file_type'], name='pbf_files_pbf_fil_837554_idx'),
        ),
        migrations.AddIndex(
            model_name='pbffile',
            index=models.Index(fields=['parent_pbf'], name='pbf_files_parent__b253b7_idx'),
        ),
        migrations.AddIndex(
            model_name='pbffile',
            index=models.Index(fields=['extraction_level'], name='pbf_files_extract_90df74_idx'),
        ),
        migrations.AddIndex(
            model_name='pbffile',
            index=models.Index(fields=['registered_at'], name='pbf_files_registe_26a429_idx'),
        ),
        migrations.AddIndex(
            model_name='osmwikidatahierarchy',
            index=models.Index(fields=['osm_relation_id'], name='osm_wikidat_osm_rel_4a02bf_idx'),
        ),
        migrations.AddIndex(
            model_name='osmwikidatahierarchy',
            index=models.Index(fields=['wikidata_id'], name='osm_wikidat_wikidat_ad46c0_idx'),
        ),
        migrations.AddIndex(
            model_name='osmwikidatahierarchy',
            index=models.Index(fields=['admin_level'], name='osm_wikidat_admin_l_a56481_idx'),
        ),
        migrations.AddIndex(
            model_name='osmwikidatahierarchy',
            index=models.Index(fields=['is_processed'], name='osm_wikidat_is_proc_b7aa4c_idx'),
        ),
        migrations.AddIndex(
            model_name='osmwikidatahierarchy',
            index=models.Index(fields=['can_generate_pickle'], name='osm_wikidat_can_gen_0d7817_idx'),
        ),
        migrations.AddIndex(
            model_name='osmwikidatahierarchy',
            index=models.Index(fields=['slug', 'admin_level'], name='osm_wikidat_slug_dada4b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='osmwikidatahierarchy',
            unique_together={('slug', 'admin_level')},
        ),
        migrations.AddIndex(
            model_name='osmboundary',
            index=models.Index(fields=['admin_level', 'name'], name='osm_boundar_admin_l_5d665c_idx'),
        ),
        migrations.AddIndex(
            model_name='osmboundary',
            index=models.Index(fields=['iso_code'], name='osm_boundar_iso_cod_4c8fb8_idx'),
        ),
    ]
