# Generated by Django 4.2.30 on 2026-08-06 00:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineLogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pipeline_run_id', models.UUIDField(blank=True, db_index=True, help_text='Denormalized for shard routing without JOIN', null=True)),
                ('step_name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('step_index', models.FloatField(blank=True, null=True)),
                ('country_code', models.CharField(blank=True, db_index=True, max_length=3, null=True)),
                ('continent', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Structured metadata: duration_ms, entity_count, error_traceback, etc.')),
                ('task_id', models.CharField(blank=True, db_index=True, help_text='Celery task ID (links to TaskResult.task_id)', max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='orchestration.pipelinerun')),
            ],
            options={
                'db_table': 'pipeline_log_entries',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['pipeline_run_id', 'timestamp'], name='pipeline_lo_pipelin_8aefcd_idx'), models.Index(fields=['country_code', 'timestamp'], name='pipeline_lo_country_6f326b_idx'), models.Index(fields=['level', 'timestamp'], name='pipeline_lo_level_b105bf_idx'), models.Index(fields=['step_name', 'timestamp'], name='pipeline_lo_step_na_699e59_idx')],
            },
        ),
    ]
