# Generated by Django 4.2.30 on 2026-08-08 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0002_add_snapshot_job'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='snapshotjob',
            new_name='snapshot_jo_snapsho_3c8881_idx',
            old_name='orch_snaps_date_status_idx',
        ),
        migrations.RenameIndex(
            model_name='snapshotjob',
            new_name='snapshot_jo_country_4bf272_idx',
            old_name='orch_snaps_cc_status_idx',
        ),
    ]
