# Generated by Django 4.2.30 on 2026-08-06 21:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0002_pipelinelogentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReasoningStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_index', models.IntegerField()),
                ('concept', models.CharField(help_text='LatentSpace enum value (semantic/geographic/ontological/topological/spectral/temporal).', max_length=32)),
                ('role', models.CharField(help_text='FunctionalRole IntEnum value (SUBCOND/COND/SUPPORT/MEASURE).', max_length=32)),
                ('operator', models.CharField(max_length=64)),
                ('envelope', models.JSONField(default=dict, help_text='Frozen, serializable OperatorEnvelope.to_dict() (v3 §2.3).')),
                ('prompt', models.TextField(blank=True, default='')),
                ('response', models.TextField(blank=True, default='')),
                ('artifacts', models.JSONField(blank=True, default=list, help_text='List of PipelineAsset.id UUIDs used/produced by this step.')),
                ('result', models.JSONField(blank=True, default=dict)),
                ('feedback', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('edited', 'Edited'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reasoning_steps',
                'ordering': ['workflow', 'step_index'],
            },
        ),
        migrations.CreateModel(
            name='ReasoningWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('geo_flow_graph', models.JSONField(default=dict, help_text='The proposed operator DAG (list of OperatorSignature-shaped dicts).')),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('executed', 'Executed'), ('failed', 'Failed')], db_index=True, default='proposed', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reasoning_workflows',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pipelineasset',
            name='continent',
            field=models.CharField(blank=True, db_index=True, help_text='Denormalized for shard routing without JOIN', max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='pipelineasset',
            index=models.Index(fields=['continent', 'asset_type'], name='pipeline_as_contine_35392a_idx'),
        ),
        migrations.AddField(
            model_name='reasoningworkflow',
            name='pipeline_run',
            field=models.ForeignKey(blank=True, help_text="Set once the workflow is executed (the dispatched Celery chain's run).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reasoning_workflows', to='orchestration.pipelinerun'),
        ),
        migrations.AddField(
            model_name='reasoningstep',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='orchestration.reasoningworkflow'),
        ),
        migrations.AddIndex(
            model_name='reasoningworkflow',
            index=models.Index(fields=['status', 'created_at'], name='reasoning_w_status_0027c6_idx'),
        ),
        migrations.AddIndex(
            model_name='reasoningworkflow',
            index=models.Index(fields=['pipeline_run'], name='reasoning_w_pipelin_b75cc2_idx'),
        ),
        migrations.AddIndex(
            model_name='reasoningstep',
            index=models.Index(fields=['workflow', 'step_index'], name='reasoning_s_workflo_39c83f_idx'),
        ),
        migrations.AddIndex(
            model_name='reasoningstep',
            index=models.Index(fields=['concept'], name='reasoning_s_concept_a93b97_idx'),
        ),
        migrations.AddIndex(
            model_name='reasoningstep',
            index=models.Index(fields=['feedback'], name='reasoning_s_feedbac_4baf89_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reasoningstep',
            unique_together={('workflow', 'step_index')},
        ),
    ]
