#!/usr/bin/env python3
"""
Import extraction metrics from JSON report to database.

This script reads the JSON extraction report generated by recursive_poly_extractor.py
and imports the metrics into the Django database, properly handling foreign key relationships.
"""

import os
import sys
import json
import django
from pathlib import Path
from datetime import datetime
from django.utils import timezone
from django.db import transaction

# Add the backend directory to Python path
backend_path = Path(__file__).parent.parent / 'backend'
sys.path.insert(0, str(backend_path))

# Setup Django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'backend.settings')
django.setup()

from api.models import PbfFile, PbfExtract, GeofabrikRegion


class ExtractionMetricsImporter:
    """Import extraction metrics from JSON report to database."""
    
    def __init__(self, json_report_path: str):
        self.json_report_path = Path(json_report_path)
        self.source_pbf_record = None
        
    def load_json_report(self) -> dict:
        """Load and parse the JSON extraction report."""
        with open(self.json_report_path, 'r') as f:
            return json.load(f)
    
    def get_or_create_source_pbf(self, source_path: str, file_size_bytes: int) -> PbfFile:
        """Get or create PbfFile record for the source file."""
        source_path = Path(source_path)
        
        # Try to find existing record
        existing = PbfFile.objects.filter(
            path=str(source_path)
        ).first()
        
        if existing:
            print(f"Found existing PbfFile record: {existing.id}")
            return existing
        
        # Create new record
        pbf_record = PbfFile.objects.create(
            pbf_file_type=PbfFile.FileType.HISTORICAL,
            status=PbfFile.PbfStatus.COMPLETED,
            path=str(source_path),
            size_bytes=file_size_bytes,
            created_at=timezone.now(),
            has_history=True,
            file_type="pbf",
            compression="bz2",
            # No geofabrik_region for local files
            geofabrik_region=None
        )
        
        print(f"Created new PbfFile record: {pbf_record.id}")
        return pbf_record
    
    def parse_datetime(self, datetime_str: str) -> datetime:
        """Parse datetime string from JSON report."""
        return datetime.fromisoformat(datetime_str.replace('Z', '+00:00'))
    
    def import_extraction_record(self, metrics: dict) -> PbfExtract:
        """Import a single extraction record to database."""
        
        # Parse datetime fields
        start_time = self.parse_datetime(metrics['start_time'])
        end_time = self.parse_datetime(metrics['end_time'])
        
        # Create PbfExtract record
        extract_record = PbfExtract.objects.create(
            source_pbf=self.source_pbf_record,
            poly_file_path=metrics['poly_path'],
            output_pbf_path=metrics['output_path'],
            source_file_size_bytes=metrics['source_file_size_bytes'],
            output_file_size_bytes=metrics['output_file_size_bytes'],
            start_time=start_time,
            end_time=end_time,
            duration_seconds=metrics['duration_seconds'],
            cpu_core_id=metrics['cpu_core_id'],
            osmium_extract_params=metrics['osmium_params'],
            osmium_time_filter_params={},  # Not used in this extraction
            task=None  # No associated task for batch processing
        )
        
        return extract_record
    
    def import_all_metrics(self) -> dict:
        """Import all extraction metrics from the JSON report."""
        print(f"Loading JSON report: {self.json_report_path}")
        
        report_data = self.load_json_report()
        detailed_metrics = report_data['detailed_metrics']
        
        print(f"Found {len(detailed_metrics)} extraction records to import")
        
        # Get source file info from first record
        first_record = detailed_metrics[0]
        source_path = first_record['source_path']
        source_size = first_record['source_file_size_bytes']
        
        # Create or get source PBF record
        print(f"Processing source file: {source_path}")
        self.source_pbf_record = self.get_or_create_source_pbf(source_path, source_size)
        
        # Import all extraction records in a transaction
        imported_count = 0
        failed_count = 0
        
        with transaction.atomic():
            for i, metrics in enumerate(detailed_metrics, 1):
                try:
                    extract_record = self.import_extraction_record(metrics)
                    imported_count += 1
                    
                    poly_name = Path(metrics['poly_path']).name
                    output_size_mb = metrics['output_file_size_bytes'] / (1024 * 1024)
                    duration_min = metrics['duration_seconds'] / 60
                    
                    print(f"[{i}/{len(detailed_metrics)}] Imported: {poly_name} "
                          f"({output_size_mb:.1f}MB, {duration_min:.1f}min) -> {extract_record.id}")
                    
                except Exception as e:
                    failed_count += 1
                    poly_name = Path(metrics['poly_path']).name
                    print(f"[{i}/{len(detailed_metrics)}] FAILED: {poly_name} - {e}")
        
        # Summary
        summary = {
            'total_records': len(detailed_metrics),
            'imported': imported_count,
            'failed': failed_count,
            'source_pbf_id': self.source_pbf_record.id,
            'extraction_summary': report_data['extraction_summary']
        }
        
        return summary


def main():
    """Main function."""
    if len(sys.argv) != 2:
        print("Usage: python import_extraction_metrics.py <json_report_path>")
        print("Example: python import_extraction_metrics.py /media/thanos/2TB_NVME/extracted_regions/extraction_report_20251019_011320.json")
        sys.exit(1)
    
    json_report_path = sys.argv[1]
    
    if not Path(json_report_path).exists():
        print(f"Error: JSON report file not found: {json_report_path}")
        sys.exit(1)
    
    try:
        importer = ExtractionMetricsImporter(json_report_path)
        summary = importer.import_all_metrics()
        
        print("\n" + "="*60)
        print("IMPORT SUMMARY")
        print("="*60)
        print(f"Total records: {summary['total_records']}")
        print(f"Successfully imported: {summary['imported']}")
        print(f"Failed: {summary['failed']}")
        print(f"Source PBF ID: {summary['source_pbf_id']}")
        
        extraction_summary = summary['extraction_summary']
        print(f"\nExtraction Summary:")
        print(f"  Total duration: {extraction_summary['total_duration_seconds']/3600:.1f} hours")
        print(f"  Total source size: {extraction_summary['total_source_size_gb']:.1f} GB")
        print(f"  Total output size: {extraction_summary['total_output_size_gb']:.1f} GB")
        print(f"  Average reduction: {extraction_summary['average_reduction_ratio']:.1%}")
        print(f"  Average rate: {extraction_summary['average_processing_rate_mb_per_sec']:.1f} MB/s")
        
        if summary['failed'] == 0:
            print("\n✅ All extraction metrics imported successfully!")
        else:
            print(f"\n⚠️  {summary['failed']} records failed to import")
            
    except Exception as e:
        print(f"Error during import: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
