# Generated by Django 4.2.30 on 2026-08-25 22:16

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('adapter_type', models.CharField(choices=[('ckan', 'CKAN'), ('socrata', 'Socrata'), ('wfs', 'WFS/WMS'), ('direct', 'Direct Download'), ('rest', 'REST API')], max_length=50)),
                ('base_url', models.URLField(max_length=1000)),
                ('api_key', models.CharField(blank=True, max_length=500, null=True)),
                ('country_code', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'geodata_source',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeoDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_dataset_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('license', models.CharField(blank=True, max_length=200)),
                ('refresh_rate', models.CharField(blank=True, max_length=100)),
                ('spatial_extent', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('temporal_start', models.DateField(blank=True, null=True)),
                ('temporal_end', models.DateField(blank=True, null=True)),
                ('keywords', models.JSONField(default=list)),
                ('is_retired', models.BooleanField(default=False)),
                ('metadata', models.JSONField(default=dict)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='geodata.datasource')),
            ],
            options={
                'db_table': 'geodata_dataset',
                'ordering': ['-last_synced_at'],
            },
        ),
        migrations.CreateModel(
            name='GeoResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_resource_id', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('format', models.CharField(db_index=True, max_length=50)),
                ('url', models.URLField(max_length=1000)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('mimetype', models.CharField(blank=True, max_length=100, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='geodata.geodataset')),
            ],
            options={
                'db_table': 'geodata_resource',
                'ordering': ['-last_modified'],
            },
        ),
        migrations.CreateModel(
            name='IngestionState',
            fields=[
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ingestion_state', serialize=False, to='geodata.georesource')),
                ('last_ingested_date', models.DateField(blank=True, null=True)),
                ('last_ingested_datetime', models.DateTimeField(blank=True, null=True)),
                ('last_ingested_count', models.IntegerField(default=0)),
                ('total_records_ingested', models.BigIntegerField(default=0)),
                ('last_ingestion_mode', models.CharField(choices=[('full', 'Full'), ('incremental', 'Incremental')], default='full', max_length=20)),
                ('last_ingestion_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'geodata_ingestion_state',
                'ordering': ['-last_ingestion_at'],
            },
        ),
        migrations.CreateModel(
            name='GeoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(db_index=True, max_length=200)),
                ('attributes', models.JSONField(default=dict)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('ingestion_date', models.DateField(blank=True, db_index=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='geodata.geodataset')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='geodata.georesource')),
            ],
            options={
                'db_table': 'geodata_record',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='DataQualitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_score_pct', models.FloatField(blank=True, null=True)),
                ('grade', models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Unknown', 'Unknown')], default='Unknown', max_length=20)),
                ('freshness', models.FloatField(blank=True, null=True)),
                ('metadata_score', models.FloatField(blank=True, null=True)),
                ('usability', models.FloatField(blank=True, null=True)),
                ('completeness', models.FloatField(blank=True, null=True)),
                ('accessibility', models.FloatField(blank=True, null=True)),
                ('qa_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_snapshots', to='geodata.geodataset')),
            ],
            options={
                'db_table': 'geodata_quality_snapshot',
                'ordering': ['-ingested_at'],
            },
        ),
        migrations.AddIndex(
            model_name='georesource',
            index=models.Index(fields=['dataset', 'format'], name='geodata_res_dataset_85dbf2_idx'),
        ),
        migrations.AddIndex(
            model_name='georecord',
            index=models.Index(fields=['resource', 'ingestion_date'], name='geodata_rec_resourc_df5e08_idx'),
        ),
        migrations.AddIndex(
            model_name='georecord',
            index=models.Index(fields=['source_id'], name='geodata_rec_source__7cdd94_idx'),
        ),
        migrations.AddIndex(
            model_name='georecord',
            index=django.contrib.postgres.indexes.GinIndex(fields=['attributes'], name='geodata_record_attrs_gin'),
        ),
        migrations.AddIndex(
            model_name='geodataset',
            index=models.Index(fields=['source', 'is_retired'], name='geodata_dat_source__d822e4_idx'),
        ),
        migrations.AddIndex(
            model_name='geodataset',
            index=models.Index(fields=['refresh_rate'], name='geodata_dat_refresh_8c5700_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='geodataset',
            unique_together={('source', 'source_dataset_id')},
        ),
        migrations.AddIndex(
            model_name='dataqualitysnapshot',
            index=models.Index(fields=['dataset', '-qa_recorded_at'], name='geodata_qua_dataset_0ea990_idx'),
        ),
    ]
