# Generated by Django 4.2.30 on 2026-10-01 15:48

from django.db import migrations, models


def _stamp_existing_bboxes(apps, schema_editor):
    """One-time provenance stamp for rows that already carry a bbox.

    Rows with a populated bbox came from the pipeline harvest path
    ('sparql'); the four subdivisions backfilled via Nominatim on
    2026-09-30 are stamped 'nominatim' explicitly.
    """
    SubgraphProfile = apps.get_model('core', 'SubgraphProfile')
    from django.utils import timezone

    now = timezone.now()
    nominatim_qids = {'Q26273', 'Q25279', 'Q21203', 'Q506049'}  # SM, CW, AW, Toledo
    rows = list(SubgraphProfile.objects.exclude(bbox_min_lon__isnull=True))
    for row in rows:
        row.bbox_source = (
            'nominatim' if row.wikidata_id in nominatim_qids else 'sparql'
        )
        row.bbox_updated_at = now
    SubgraphProfile.objects.bulk_update(rows, ['bbox_source', 'bbox_updated_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgraphprofile',
            name='bbox_source',
            field=models.CharField(blank=True, db_index=True, default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='subgraphprofile',
            name='bbox_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(_stamp_existing_bboxes, migrations.RunPython.noop),
    ]
