# Generated by Django 4.2.30 on 2026-08-03 20:33

from django.db import migrations, models
import pgvector.django


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OsmEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField(help_text="Unique OSM tag, e.g., 'amenity=school'", unique=True)),
                ('embedding', pgvector.django.VectorField(dimensions=300)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Optional metadata from OSM', null=True)),
            ],
            options={
                'verbose_name': 'OSM Embedding',
                'verbose_name_plural': 'OSM Embeddings',
                'indexes': [models.Index(fields=['tag'], name='vectors_osm_tag_1fa671_idx')],
            },
        ),
    ]
